stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./varnish/Dockerfile
      buildContext: ./varnish
      tag: varnish:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
