kind: Service
apiVersion: v1
metadata:
  name: varnish-service
spec:
  selector:
    app: varnish
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
  labels:
    app: varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varnish
  template:
    metadata:
      labels:
        app: varnish
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: varnish
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        env:
        - name: VIRTUAL_HOST
          value: "varnish"
        - name: VIRTUAL_PORT
          value: "80"
        - name: HTTPS_METHOD
          value: "noredirect"
        ports:
        - containerPort: 80

